apiVersion: v1
kind: Service
metadata:
  name: fittnessduel-service
  namespace: default
spec:
  selector:
    app: fittnessduel
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
